### ISSUE TITLE
I can not find this repository in github by search

### ISSUE THREAD

**Issue by Auzout** [komsa-ag/Camunda.Api.Client#9]
If I search "Camunda.Api.Client", I only get 3 C# repository, this project is not included. But since the original project is not maintained anymore, it's unfair for forked project lives under the shadow of it. Will remove the "forked from" help?

**Comment by christiankittel** [comment]
Hi,
this is a good idea. I will discuss this with my colleagues

**Comment by christiankittel** [comment]
We have detached this repo from the original one.
